-- Create table for Akta Perkawinan
CREATE TABLE IF NOT EXISTS akta_perkawinan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_akta TEXT NOT NULL,
    nama_suami TEXT NOT NULL,
    nama_istri TEXT NOT NULL,
    tanggal_terbit DATE NOT NULL,
    agama TEXT NOT NULL,
    foto_dokumen TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE akta_perkawinan ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON akta_perkawinan
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON akta_perkawinan
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON akta_perkawinan
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Enable delete for authenticated users only" ON akta_perkawinan
    FOR DELETE TO authenticated USING (true);
