-- Create akta_perceraian table
CREATE TABLE IF NOT EXISTS akta_perceraian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_akta TEXT NOT NULL,
    nama_suami TEXT NOT NULL,
    nama_istri TEXT NOT NULL,
    tanggal_terbit DATE NOT NULL,
    keterangan TEXT,
    deret TEXT,
    foto_dokumen TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE akta_perceraian ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access (for development speed, as requested previously implied)
CREATE POLICY "Enable all access for all users" ON akta_perceraian
    FOR ALL
    USING (true)
    WITH CHECK (true);
