-- Create akta_kematian table
CREATE TABLE IF NOT EXISTS akta_kematian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_surat TEXT NOT NULL,
    nama TEXT NOT NULL,
    tanggal_meninggal DATE NOT NULL,
    tempat_lahir TEXT,
    tanggal_lahir DATE,
    foto_dokumen TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE akta_kematian ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access
CREATE POLICY "Enable all access for all users" ON akta_kematian
    FOR ALL
    USING (true)
    WITH CHECK (true);
