-- Create activity_logs table
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT, -- Store display name for easier reading
    action TEXT NOT NULL, -- e.g. "TAMBAH DATA", "HAPUS DATA"
    details TEXT, -- e.g. "Menambahkan KK No. 12345"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to insert logs
CREATE POLICY "Enable insert for authenticated users only" ON activity_logs
    FOR INSERT TO authenticated WITH CHECK (true);

-- Allow authenticated users to view logs
CREATE POLICY "Enable select for authenticated users only" ON activity_logs
    FOR SELECT TO authenticated USING (true);
